#!/system/bin/sh
# sy

# All hail busybox for standardising this script!
busybox=/sbin/.core/busybox
oPATH=$PATH
PATH=$busybox:$oPATH
set -o pipefail

# Check if run under root --------------------------------
if ! ls /data > /dev/null 2> /dev/null; then
    echo "[!] ERROR"
    echo "    ts-encfs needs to be invoked"
    echo "    from an elevated shell."
    echo "    Please run 'su' first."
    echo
    echo "Terminating.."
    exit 1
fi

# Functions ----------------------------------------------
MODDIR=/sbin/.core/img/ts-encfs
datadir=/data/ts-encfs
int=/mnt/runtime/default/emulated/0
intraw=/data/media/0
sdname=$(grep -m 1 "/mnt/media_rw/" /proc/mounts | grep -m 1 -Eo "[0-9A-Z]{4}-[0-9A-Z]{4}")
sd=/mnt/runtime/default/$sdname
folderlist=$datadir/cached-folderlist.sh
folderlistuser=$intraw/ts-encfs-folderlist.txt
password=

supass() {
    /sbin/su -M -c "$*"
}

printhelp() {
    echo "tsencfs [options] ([arg] [arg2])"
    echo
    echo "Available options:"
    echo
    echo "(help | h | --help | -h)"
    echo "      Show this reference text"
    echo "-x   [pair name]"
    echo "      Mounts the pair as configured"
    echo "      in the folderlist"
    echo "-u   [pair name]"
    echo "      Unmounts the pair as configured"
    echo "      in the folderlist"
}

# No action given ----------------------------------------
if [ ! "$1" ]; then
    echo "E: No action is declared!"
    echo ''
    printhelp

# Print Help ---------------------------------------------
elif [ "$1" = "help" ] || [ "$1" = "h" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    printhelp

# Mount --------------------------------------------------
elif [ "$1" = "mount" ]; then
    folderbind() {
        if supass mountpoint -q \""$3"\"; then
            echo "$1 is already mounted"
        elif [ ! -d "$2" ]; then
            echo "Mount aborted: Directory '$2' as source doesn't exist!"
            exit 1
        else
            echo "Mounting $1"
            if { supass echo \""$4"\" | encfs -S --public \""$2"\" \""$3"\" }; then
                if { echo "$3" | grep -q "$sd"; }; then
                    sdraw="$(echo "$3" | sed 's/\/mnt\/runtime\/default/\/mnt\/media_rw/g')"
                    { supass encfs -S --public \""$2"\" \""$3"\"; } || exit 1
                fi
                echo "Bind successful"
            else
                echo "Bind failed"
                exit 1
            fi
        fi
    }
    if [ ! "$2" ]; then
        echo 'E: Bind name is not provided!'
    elif [ "$2" = "all" ]; then
        echo "Binding all entries"
        . $folderlist
        echo "All entries were processed"
    elif [ "$2" = "o" ]; then
        folderbind "o" "$3" "$4"
    elif line="$(grep -m 1 "$2" $folderlist)"; then
        eval "$line"
    else
        echo "Unable to bind $2, entry not found in list!"
    fi

# Action unrecognised ------------------------------------
else
    echo "E: Unknown action \"$1\" supplied"
    echo 'Run "tsbinds h" or "tsbinds help" for help'
fi

# Handover default PATH ----------------------------------
# in case somebody sourced this fakebin
PATH=$oPATH
set +o pipefail

# Return true if script reaches here ---------------------
exit 0